### ISSUE TITLE
Add UI 

### ISSUE THREAD

**Issue by stefaniepires** [steftinsley/weather-dashboard#3]
Add UI for all features

**Comment by GustavoTxFreitas-zz** [comment]
## Hello, @steftinsley!
What are your ideas for designing your app's UI?
I’d be very happy to contribute to your repository.

Tell me about this project, you can contact me by this issue or by my [email](dev.gustavotxfreitas@gmail.com)!
See you soon, [Gustavo Teixeira](https://github.com/GustavoTxFreitas).

**Comment by stefaniepires** [comment]
Hello @GustavoTxFreitas, 

Thank you for reaching out! I am working on this app for a class assignment and need to be the only contributor. 

Maybe for future projects!

Best, 
Stefanie.
